### ISSUE TITLE
コード規約

### ISSUE THREAD

**Issue by nappannda** [taku178/SojoARApp#4]

**Comment by Taku24** [comment]
今日の昼休みで対応しよう

**Comment by nappannda** [comment]
コード規約
* https://source.android.com/source/code-style


コードチェック参考
* http://qiita.com/shiraji/items/03be03a9b1cbe5ecc433

@Taku24 これどうっすか　コード規約の日本語訳なくなってた…

**Comment by Taku24** [comment]
一通り確認したけど、コードチェック参考は何個かピックアップして入れるべきだと思う。コードを書く人によってインデント等が違ったりすると可読性が薄まるし。

コード規約はどうしよ、日本語訳がないとちゃんとした内容を理解できないしフィーリングでレビューしていく感じになると思うけどそれでもいいのならそれを採用しよう

**Comment by nappannda** [comment]
コードチェックのやつはコード規約を基に設定するんやで…
コード規約他にもあるし日本語のやつあとで何個か貼るわ

**Comment by nappannda** [comment]
GoogleのJavaコーディング規約の非公式和訳
https://kazurof.github.io/GoogleJavaStyle-ja/
Android側のコーディング規約
http://qiita.com/Reyurnible/items/c2c0f7150d338a49de86

この２つ使うのどうっすか @Taku24

**Comment by Taku24** [comment]
いいと思います、さっそく導入しましょう

**Comment by nappannda** [comment]
とりあえず今回の規約に沿うようなlint導入する

参考URL
https://developer.android.com/studio/write/lint.html?hl=ja

**Comment by Taku24** [comment]
ざっとみた感じやと、これって各個人で導入する必要あり？？

**Comment by nappannda** [comment]
設定ファイルこっちで作るけどビルド時に実行させる設定は共有されないから一回設定しなきゃいけないかも
特にめんどくさい設定はないはず

**Comment by Taku24** [comment]
了解です、ならSlackのgeneralに今回の趣旨を伝えてください...

**Comment by nappannda** [comment]
今回の趣旨ってなんや…

**Comment by Taku24** [comment]
・コード規約を設けること、理由
・コード規約の内容
・設定方法
主にこの3点かな

**Comment by nappannda** [comment]
コード規約を設ける理由と内容はかけるっちゃかけるけど
設定方法が今怪しいのでTravisCIでリモートに上がったあと規約的におかしいコードをプルリクで自動指摘するようにしようかな

**Comment by Taku24** [comment]
リモートの方が楽だからそれを採用しよう

**Comment by nappannda** [comment]
じゃあTravisCIの調査してくる
